version: '3'

services:
  database:
    image: redis
    volumes:
      - ./data:/data

  web:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      REDIS_URL: database
      FLASK_DEBUG: 1
      FLASK_APP: app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"